import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    files: ["wwwroot/**/*.js"],
    ignores: ["wwwroot/vendor/**"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...globals.browser,

        // Vendor libraries
        Vue: "readonly",
        createApp: "readonly",
        reactive: "readonly",
        nextTick: "readonly",
        jQuery: "readonly",
        $: "readonly",
        Decimal: "readonly",
        flatpickr: "readonly",
        signalR: "readonly",
        HubConnectionBuilder: "readonly",
        bootstrap: "readonly",
        Tooltip: "readonly",
        i18next: "readonly",
        i18nextHttpBackend: "readonly",
        hljs: "readonly",
        Chart: "readonly",
        Chartist: "readonly",
        Papa: "readonly",
        vex: "readonly",
        TomSelect: "readonly",
        Sortable: "readonly",
        confetti: "readonly",
        anime: "readonly",
        saveAs: "readonly",
        BBQR: "readonly",
        URRegistry: "readonly",
        VueQrcodeReader: "readonly",
        VueSanitize: "readonly",
        VueQrcode: "readonly",
        VueSanitizeDirective: "readonly",
        Blazor: "readonly",
        Shopify: "readonly",
        NDEFReader: "readonly",

        // Razor view injected globals (via inline <script> in .cshtml)
        srvModel: "readonly",
        initialSrvModel: "readonly",
        initialConfig: "readonly",
        availableLanguages: "readonly",
        checkoutBaseUrl: "readonly",
        statusUrl: "readonly",
        statusWsUrl: "readonly",
        i18nUrl: "readonly",
        lnurlEndpoint: "readonly",
        srv: "readonly",

        // Project globals (utils.js, site.js, etc.)
        initLabelEditModal: "writable",
        startAuthCheck: "writable",
        inputChanges: "writable",
        registerTooltipDirective: "writable",
        posCommon: "writable",
        posOrder: "writable",
        PoSOrder: "writable",
        eventAggregator: "writable",
        createEventBus: "writable",
        createHubListener: "writable",
        showToast: "writable",
        createToastContainer: "writable",
        playSound: "writable",
        playRandomSound: "writable",
        vault: "writable",
        confirmCopy: "writable",
        copyToClipboard: "writable",
        copyUrlToClipboard: "writable",
        getInvoiceUrl: "writable",
        getExplorerUrl: "writable",
        fireworks: "writable",
        __checkoutNfcBus: "writable",
        delegate: "writable",
        debounce: "writable",
        formatLongDate: "writable",
        formatFullDateTime: "writable",
        formatShortDateTime: "writable",
        formatCSVDateTime: "writable",
        timeAgo: "writable",
        calendarDate: "writable",
        toUnix: "writable",
        fromUnix: "writable",
        endOfDayUnix: "writable",
        formatDateTimes: "writable",
        noExponents: "writable",
        timeDiffString: "writable",
        POS_ITEM_ADDED_CLASS: "writable",
        storageKey: "writable",
        saveState: "writable",
        loadState: "writable",
        baseUrl: "writable",
        flatpickrInstances: "writable",
        collapsibleDirective: "writable",
        sanitizeDirective: "writable",
        registerCollapsibleDirective: "writable",
        registerSortableDirective: "writable",
        setColorMode: "writable",
        hubListener: "writable",
        btcpay: "writable",
        initCameraScanningApp: "writable",
        createTable: "writable",
        filter: "writable",
        clone: "writable",
        isSafari: "writable",

        // WebAuthn globals
        coerceToArrayBuffer: "writable",
        coerceToBase64Url: "writable",
        detectFIDOSupport: "writable",
        showErrorAlert: "writable",
        value: "writable",
        makeAssertionOptions: "readonly",
        makeCredentialOptions: "readonly",
      },
    },
    rules: {
      "no-var": "error",
      "prefer-const": "warn",
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none" }],
      "no-undef": "error",
      "no-redeclare": ["error", { builtinGlobals: false }],
      "no-duplicate-case": "error",
      "no-dupe-keys": "error",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-prototype-builtins": "warn",
      "eqeqeq": ["warn", "smart"],
      "no-debugger": "warn",
      "no-alert": "warn",
    },
  },
  {
    files: [
      "wwwroot/main/utils.js",
      "wwwroot/js/webauthn/helpers.js",
      "wwwroot/js/vue-utils.js",
      "wwwroot/js/event-bus.js",
      "wwwroot/js/label-edit-modal.js",
      "wwwroot/js/lnurl-auth-check.js",
      "wwwroot/js/signalr-hub-listener.js",
      "wwwroot/js/toast-utils.js",
      "wwwroot/js/vaultbridge.js",
      "wwwroot/crowdfund/services/audioplayer.js",
      "wwwroot/crowdfund/services/listener.js",
      "wwwroot/payment-request/services/listener.js",
      "wwwroot/pos/common.js",
      "wwwroot/paybutton/paybutton.js",
    ],
    rules: {
      "no-unused-vars": "off",
    },
  },
  {
    ignores: ["wwwroot/vendor/**"],
  },
];
